### ISSUE TITLE
循环回自己时会卡死超时

### ISSUE THREAD

**Issue by wangjiba** [ladybugflow/ladybugflow#1]
例如这样会直接卡死没反应：
Like this will timeout ：
 
start --> nodeA -(0)-> nodeC
start --> nodeA -(1)-> nodeB --> nodeA

**Comment by ladybugflow** [comment]
节点默认Wait All的话，会等待所有前节点处理完后，才会执行。
下图节点A修改成 Wait One，可以避免卡死的状况，但是目前版本也不会循环执行，执行节点B后即结束（因为A已经执行过了，目前版本没有对应重复执行，后续版本会考虑增加可重复执行的需求）
![image](https://user-images.githubusercontent.com/39003621/222723130-cf5c968e-4278-49e6-8553-6324079830be.png)
