### ISSUE TITLE
外部参数怎么传入流程节点中，使用ThreadLocal方式获取不到外部设置的值。

### ISSUE THREAD

**Issue by wangjiba** [ladybugflow/ladybugflow#2]
![8b4a56d7869c156adc460222350874f](https://user-images.githubusercontent.com/8586668/222758902-42b15aff-ec90-47a4-bfd6-e8ce42e8744d.png)

![image](https://user-images.githubusercontent.com/8586668/222759815-ba4cc87f-dfde-494e-bae0-b57d124fd218.png)

**Comment by ladybugflow** [comment]
CommonOneFlow在运行时只有一个实例，直接用类变量传参就可以。（不建议用ThreadLocal传参，因为运行时有多个线程调用一个CommonOneFlow实例）
比如在class CommonOneFlow中加入类变量：private String controllerId；
和设值方法setControllerId，流程启动后在外面调用setControllerId，里面就可以取得值。方法间传参也同理。

**Comment by wangjiba** [comment]
这样我是将其注入的，不是new出来的，私有变量线程不安全，后面访问会拿到上次设置的私有变量
   @Autowired
   private CommonOneFlow commonOneFlow;
   
   @GetMapping("testFlow")
    @ResponseBody
    public R oneFlow( ){
          commonOneFlow.setControllerId("11");  //非安全
          commonOneFlow.startFlow(true);
    }

**Comment by ladybugflow** [comment]
现版本，流程的状态在new的时候初始化，并没有在startFlow的时候进行初始化， 
所以注入的commonOneFlow多次调用startFlow的话，第一次以外的流程状态没有初始化，不能保证流程能正常执行。
现阶段建议new出来CommonOneFlow。
->后续我们针对此点进行改进。

针对私有变量的线程不安全，建议用一些方法（比如AtomicReference关键字）控制变量读取的线程安全性。
->后续我们针对此点进行改进。
